name: 'Create or Update Comment'
description: 'Create or update an issue or pull request comment'
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
  repository:
    description: 'The full name of the repository in which to create or update a comment.'
    default: ${{ github.repository }}
  issue-number:
    description: 'The number of the issue or pull request in which to create a comment.'
  comment-id:
    description: 'The id of the comment to update.'
  body:
    description: 'The comment body. Cannot be used in conjunction with `body-path`.'
  body-path:
    description: 'The path to a file containing the comment body. Cannot be used in conjunction with `body`.'
  body-file:
    description: 'Deprecated in favour of `body-path`.'
  edit-mode:
    description: 'The mode when updating a comment, "replace" or "append".'
    default: 'append'
  append-separator:
    description: 'The separator to use when appending to an existing comment. (`newline`, `space`, `none`)'
    default: 'newline'
  reactions:
    description: 'A comma or newline separated list of reactions to add to the comment.'
  reactions-edit-mode:
    description: 'The mode when updating comment reactions, "replace" or "append".'
    default: 'append'
outputs:
  comment-id:
    description: 'The id of the created comment'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'message-square'
  color: 'gray-dark'
